// seedproject.ts

export const projects = [
    {
      projectTitle: 'Project 1',
      commitHours: '10',
      companyName: 'Company A',
      website: 'https://companya.com',
      contactPerson: 'John Doe',
      primaryPhoneNumber: '123-456-7890',
      mobileNumber: '987-654-3210',
      bestTimesToContact: 'Weekdays, 9 AM - 5 PM',
      email: 'john@companya.com',
      businessAddress: '123 Main St',
      city: 'City A',
      state: 'State A',
      zip: '12345',
      country: 'Country A',
      description: 'This is project 1 description.',
      isRRCStudent: false,
      rrcProgram: null,
      isNorthForge: true,
      northForgeProgram: 'Program X',
      isIndigenousOwned: false,
      indigenousFocus: false,
      businessIdea: 'Idea for Project 1',
      serviceDescription: 'Service Description for Project 1',
      // Add more properties as needed
    },
    {
      projectTitle: 'Project 2',
      commitHours: '15',
      companyName: 'Company B',
      website: 'https://companyb.com',
      contactPerson: 'Jane Smith',
      primaryPhoneNumber: '987-654-3210',
      mobileNumber: '123-456-7890',
      bestTimesToContact: 'Weekdays, 10 AM - 6 PM',
      email: 'jane@companyb.com',
      businessAddress: '456 Elm St',
      city: 'City B',
      state: 'State B',
      zip: '54321',
      country: 'Country B',
      description: 'This is project 2 description.',
      isRRCStudent: true,
      rrcProgram: 'Program Y',
      isNorthForge: false,
      northForgeProgram: null,
      isIndigenousOwned: true,
      indigenousFocus: true,
      businessIdea: 'Idea for Project 2',
      serviceDescription: 'Service Description for Project 2',
      // Add more properties as needed
    },
    // Add more project objects as needed
    {
      projectTitle: 'Project 3',
      commitHours: '20',
      companyName: 'Company C',
      website: 'https://companyc.com',
      contactPerson: 'Mike Johnson',
      primaryPhoneNumber: '555-123-4567',
      mobileNumber: '555-987-6543',
      bestTimesToContact: 'Weekdays, 8 AM - 4 PM',
      email: 'mike@companyc.com',
      businessAddress: '789 Oak St',
      city: 'City C',
      state: 'State C',
      zip: '67890',
      country: 'Country C',
      description: 'This is project 3 description.',
      isRRCStudent: false,
      rrcProgram: null,
      isNorthForge: false,
      northForgeProgram: null,
      isIndigenousOwned: false,
      indigenousFocus: false,
      businessIdea: 'Idea for Project 3',
      serviceDescription: 'Service Description for Project 3',
      // Add more properties as needed
    },
  ];
  