-- CreateTable
CREATE TABLE "IndustryProject" (
    "id" SERIAL NOT NULL,
    "projectTitle" TEXT NOT NULL,
    "commitHours" TEXT NOT NULL,
    "companyName" TEXT NOT NULL,
    "website" TEXT,
    "contactPerson" TEXT NOT NULL,
    "primaryPhoneNumber" TEXT NOT NULL,
    "mobileNumber" TEXT,
    "bestTimesToContact" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "businessAddress" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "zip" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "isRRCStudent" BOOLEAN NOT NULL,
    "rrcProgram" TEXT,
    "isNorthForge" BOOLEAN NOT NULL,
    "northForgeProgram" TEXT,
    "isIndigenousOwned" BOOLEAN NOT NULL,
    "indigenousFocus" BOOLEAN NOT NULL,
    "businessIdea" TEXT NOT NULL,
    "serviceDescription" TEXT NOT NULL,
    "strategicPriorities" TEXT NOT NULL,
    "problemToSolve" TEXT NOT NULL,
    "valueProposition" TEXT NOT NULL,
    "successMetrics" TEXT NOT NULL,
    "customerBenefits" TEXT NOT NULL,
    "impactOfOpportunity" TEXT NOT NULL,
    "customers" TEXT NOT NULL,
    "currentMarketing" TEXT NOT NULL,
    "deliveryMethod" TEXT NOT NULL,
    "adoptionApproach" TEXT NOT NULL,
    "keyUsers" TEXT NOT NULL,
    "alternativeUsage" TEXT NOT NULL,
    "businessCase" TEXT,
    "appliedForGrant" BOOLEAN NOT NULL,
    "grantDetails" TEXT,
    "studentFunding" BOOLEAN NOT NULL,
    "fundingAmount" TEXT,
    "receiveInfo" BOOLEAN NOT NULL,
    "anticipatedLength" TEXT NOT NULL,
    "featureSet" TEXT NOT NULL,
    "technologyEnvironment" TEXT NOT NULL,
    "studentEnticement" TEXT NOT NULL,
    "learningOutcomes" TEXT NOT NULL,
    "additionalComments" TEXT,

    CONSTRAINT "IndustryProject_pkey" PRIMARY KEY ("id")
);
